use crate::models::*;

use dioxus::prelude::*;
use crate::asset;
/// Returns a sample list of Wandertouren for demonstration purposes.

pub fn get_sample_tours() -> Vec<Wandertour> {
    vec![
        Wandertour {
            id: 1,
            name: "Alpenpanorama-Route".to_string(),
            beschreibung: "Eine spektakuläre Wanderung durch die Alpen mit atemberaubenden Ausblicken auf die Gipfel.".to_string(),
            schwierigkeitsgrad: "Mittel".to_string(),
            etappen: vec![
                Etappe {
                    id: 1,
                    name: "Aufstieg zur Alpspitze".to_string(),
                    beschreibung: "Aufstieg zum Berggasthof mit herrlichem Blick ins Tal".to_string(),
                    laenge_km: 8.5,
                    steigung_hm: 600,
                    abstieg_hm: 100,
                    startort: "Garmisch-Partenkirchen".to_string(),
                    zielort: "Berggasthof Alpspitze".to_string(),
                    start_gps: GpsCoordinate::new(47.4924, 11.0955),
                    ziel_gps: GpsCoordinate::new(47.4712, 11.0634),
                },
                Etappe {
                    id: 2,
                    name: "Kammwanderung zum Ehrwalder Alm".to_string(),
                    beschreibung: "Kammwanderung mit Panoramablick über das Wettersteingebirge".to_string(),
                    laenge_km: 12.2,
                    steigung_hm: 400,
                    abstieg_hm: 800,
                    startort: "Berggasthof Alpspitze".to_string(),
                    zielort: "Ehrwald".to_string(),
                    start_gps: GpsCoordinate::new(47.4712, 11.0634),
                    ziel_gps: GpsCoordinate::new(47.4006, 10.9134),
                },
            ],
            images: vec![],
        },
        Wandertour {
            id: 2,
            name: "Schwarzwald-Rundweg".to_string(),
            beschreibung: "Gemütliche Wanderung durch die dichten Wälder des Schwarzwalds mit traditionellen Dörfern.".to_string(),
            schwierigkeitsgrad: "Leicht".to_string(),
            etappen: vec![
                Etappe {
                    id: 3,
                    name: "Waldwanderung durch den Tannenwald".to_string(),
                    beschreibung: "Waldwanderung durch Tannen- und Buchenwälder".to_string(),
                    laenge_km: 6.8,
                    steigung_hm: 200,
                    abstieg_hm: 150,
                    startort: "Triberg".to_string(),
                    zielort: "Schönbuch".to_string(),
                    start_gps: GpsCoordinate::new(48.1293, 8.2277),
                    ziel_gps: GpsCoordinate::new(48.1456, 8.2891),
                },
                Etappe {
                    id: 4,
                    name: "Besuch der Triberger Wasserfälle".to_string(),
                    beschreibung: "Besuch traditioneller Schwarzwaldhöfe und Wasserfälle".to_string(),
                    laenge_km: 9.3,
                    steigung_hm: 300,
                    abstieg_hm: 350,
                    startort: "Schönbuch".to_string(),
                    zielort: "Sankt Georgen".to_string(),
                    start_gps: GpsCoordinate::new(48.1456, 8.2891),
                    ziel_gps: GpsCoordinate::new(48.1249, 8.3283),
                },
            ],
            images: vec![],
        },
        Wandertour {
            id: 3,
            name: "Rheinsteig-Tour".to_string(),
            beschreibung: "Wanderung entlang des Rheins mit Burgen, Weinbergen und malerischen Aussichtspunkten.".to_string(),
            schwierigkeitsgrad: "Mittel".to_string(),
            etappen: vec![
                Etappe {
                    id: 5,
                    name: "Aufstieg zur Burg Rheinfels".to_string(),
                    beschreibung: "Aufstieg zur Burg Rheinfels mit Blick auf den Rhein".to_string(),
                    laenge_km: 11.7,
                    steigung_hm: 450,
                    abstieg_hm: 200,
                    startort: "Sankt Goar".to_string(),
                    zielort: "Bacharach".to_string(),
                    start_gps: GpsCoordinate::new(50.1506, 7.7133),
                    ziel_gps: GpsCoordinate::new(50.0587, 7.7694),
                },
                Etappe {
                    id: 6,
                    name: "Weinwanderung nach Bingen".to_string(),
                    beschreibung: "Wanderung durch Weinberge und historische Städtchen".to_string(),
                    laenge_km: 14.2,
                    steigung_hm: 380,
                    abstieg_hm: 420,
                    startort: "Bacharach".to_string(),
                    zielort: "Bingen".to_string(),
                    start_gps: GpsCoordinate::new(50.0587, 7.7694),
                    ziel_gps: GpsCoordinate::new(49.9697, 7.8956),
                },
            ],
            images: vec![],
        },
        Wandertour {
            id: 4,
            name: "Alpenüberquerung für Anfänger (Tegernsee-Sterzing)".to_string(),
            beschreibung: "Gemütlich zu Fuß über die Alpen mit Gepäcktransport".to_string(),
            schwierigkeitsgrad: "Mittel".to_string(),
            etappen: vec![
                Etappe {
                    id: 11,
					name: "Kennenlernen am Tegernsee".to_string(),
                    beschreibung: "Vom Bahnhof laufen wir den informativen Lärchenweg bis zur Halbinsel, wo das Ruderboot ablegt. Mit diesem überqueren wir den Tegernsee und lernen uns an Bord schon einmal kennen. Schließlich wandern wir nun eine Woche gemeinsam über die Alpen. In Rottach-Egern ist unsere Fahrt zu Ende und wir wandern gemütlich entlang der Weißach bis nach Kreuth zu unserem traditionsreichen Hotel zur Post. Der schattige Waldweg am Bach entlang ist genau der richtige Einstieg.".to_string(),
                    laenge_km: 11.0,
                    steigung_hm: 110,
                    abstieg_hm: 80,
                    startort: "Tegernsee, Bahnhof".to_string(),
                    zielort: "Kreuth".to_string(),
                    start_gps: GpsCoordinate::new(47.7143, 11.7572),
                    ziel_gps: GpsCoordinate::new(47.6454, 11.7452),
                },
                Etappe {
                    id: 12,
					name: "Kreuth - Achenwald - Achenkirch".to_string(),
                    beschreibung: "Transfer nach Wildbad-Kreuth. Von dort aus wandern wir auf einem schönen Steig und erreichen schließlich das Almgelände der Königsalm. Nicht mehr lang und schon überqueren wir die Bayrisch-Tiroler Grenze. Auf Tiroler Seite sehen wir schon die Blauberg Alm. Hier bieten sich verschiedene Almen zur gemütlichen Einkehr an. Durch Wald- und Wiesengelände führt der Weg schließlich hinab bis nach Achenwald. Für die Strecke bis nach Achenkirch nutzen wir einen Linienbus zu unserer Unterkunft, das Resort Achensee by VAYA.".to_string(),
                    laenge_km: 17.2,
                    steigung_hm: 920,
                    abstieg_hm: 890,
                    startort: "Wanderparkplatz Siebenhütten, Wildbad-Kreuth".to_string(),
                    zielort: "Achenwald".to_string(),
                    start_gps: GpsCoordinate::new(47.6221, 11.7350),
                    ziel_gps: GpsCoordinate::new(47.5667, 11.6705),
                },
				Etappe {
                    id: 13,
					name: "Achenkirch - Maurach - Pertisau - Inntal - Fügen".to_string(),
                    beschreibung: "Der Weg entlang des Achensees ist zurecht einer der schönsten Wanderwege in Tirol. Wir wandern stets am Ufer oder einige Meter oberhalb am See entlang. Unterwegs stürzen immer wieder Wasserfälle in den See und über uns hinweg. Der Weg ist angenehm zu gehen und an einigen Stellen, an denen es etwas schmaler wird, sind Seile zur Sicherung angebracht. So geht es dahin bis Pertisau. In diesem kleinen Ort haben wir die Möglichkeit einzukehren. Es folgt noch eine weitere kurze Wanderung bis zum Seespitz. Hier holt uns ein Taxi ab und bringt uns nach Fügen in unser 4-Sterne-Hotel, das Hotel KOSIS.".to_string(),
                    laenge_km: 13.1,
                    steigung_hm: 200,
                    abstieg_hm: 200,
                    startort: "VAYA-Resort Achenkirch".to_string(),
                    zielort: "Maurach Achensee Seespitz".to_string(),
                    start_gps: GpsCoordinate::new(47.5102, 11.7093),
                    ziel_gps: GpsCoordinate::new(47.4253, 11.7329),
                },
				Etappe {
                    id: 14,
					name: "Fügen - Spieljoch - Hochfügen".to_string(),
                    beschreibung: "Die Spieljochbahn bringt uns heute auf Augenhöhe mit den großen Gipfeln und eröffnet uns ein großartiges Panorama in die angrenzenden Gebirgsgruppen - Karwendel - Rofan - Wilder Kaiser und natürlich die Zillertaler Alpen. Durch eine märchenhafte Landschaft, die wie von Trollen geschaffen wirkt, wandern wir bis zur Gartalm. Eine Einkehr ist Gewiss! Gemütlich geht es dann noch bis nach Hochfügen, wo uns in unserem 4-Sterne-Hotel, dem Zirbenhof Hochfügen, ein besonderer Rückzugsort erwartet.".to_string(),
                    laenge_km: 13.8,
                    steigung_hm: 380,
                    abstieg_hm: 740,
                    startort: "Hotel KOSIS, Fügen".to_string(),
                    zielort: "Hochfügen".to_string(),
                    start_gps: GpsCoordinate::new(47.34732, 11.8485),
                    ziel_gps: GpsCoordinate::new(47.27086, 11.777773),
                },
				Etappe {
                    id: 15,
					name: "Hochfügen - Pfundsalm - Rastkogelhütte - Mayrhofen".to_string(),
                    beschreibung: "Heute geht es durch die traditionellen Almdörfer der Pfundsalm (Nieder- und Hochleger), die typisch für das Zillertal sind, vorbei an plattigen Gletscherschliffen bis auf das Sidanjoch und weiter zur Rastkogelhütte. Nun weiter auf einen schönen Gipfel und mit großartiger Aussicht hinab bis nach Melchboden an der Zillertaler Höhenstraße. Mit dem Linienbus und der Zillertalbahn fahren wir nach Mayrhofen, dem Hauptort des Zillertals.".to_string(),
                    laenge_km: 11.5,
                    steigung_hm: 740,
                    abstieg_hm: 240,
                    startort: "Zirbenhof, Hochfügen".to_string(),
                    zielort: "Melchboden".to_string(),
                    start_gps: GpsCoordinate::new(47.27086, 11.777773),
                    ziel_gps: GpsCoordinate::new(47.2183, 11.8237),
                },
				Etappe {
                    id: 16,
					name: "Schlegeis-Stausee - Pfitscherjoch - Stein - Sterzing".to_string(),
                    beschreibung: "Mit dem Taxi geht es zum Schlegeis-Stausee. Die Gletscher der südlichen Zillertaler scheinen von hier zum Greifen nah! Den Alpenhauptkamm überqueren wir nun am Pfitscherjoch. Kurz nach der Grenze liegt schön das Pfitscherjochhaus auf italienischer Seite und erwartet uns mit der landestypischen Küche. Über weite Almen und Wald wandern wir hinab bis nach Stein. Hier holt uns ein Taxi ab und wir fahren in unsere Unterkunft. Stolz, die Tour geschafft zu haben, lassen wir den letzten Tag verdient gemütlich ausklingen. Übernachtung in Steindls Boutique-Hotel in Sterzing.".to_string(),
                    laenge_km: 9.5,
                    steigung_hm: 500,
                    abstieg_hm: 730,
                    startort: "Parkplatz Schlegeisspeicher Zamsereck".to_string(),
                    zielort: "Stein, Sasso (Südtirol)".to_string(),
                    start_gps: GpsCoordinate::new(47.02941, 11.6954),
                    ziel_gps: GpsCoordinate::new(46.9795, 11.6332),
                },
				Etappe {
                    id: 17,
					name: "Sterzing - Inntal - Tegernsee".to_string(),
                    beschreibung: "Nach dem Frühstück werden wir abgeholt und fahren mit einem privatem Transfer von Sterzing zurück an den Tegernsee. Die Route folgt dem Brenner bis Innsbruck und führt dann über den Achensee zurück an den Tegernsee. Die Fahrzeit beträgt in der Regel 2,5-3 Stunden.".to_string(),
                    laenge_km: 0.0,
                    steigung_hm: 0,
                    abstieg_hm: 0,
                    startort: "Steindls Boutique-Hotel, Sterzing".to_string(),
                    zielort: "Tegernsee, Bahnhof".to_string(),
                    start_gps: GpsCoordinate::new(46.9018, 11.4296),
                    ziel_gps: GpsCoordinate::new(47.7143, 11.7572),
                },
            ],
            images: vec![
                TourImage {
                    src: asset!("assets/images/tour4/Tegernsee.jpg").to_string(),
                    alt: "Tegernsee".to_string(),
                    caption: "Start am malerischen Tegernsee in Bayern.".to_string(),
                },
                TourImage {
                    src: asset!("assets/images/tour4/1201Achensee.jpg").to_string(),
                    alt: "Achensee".to_string(),
                    caption: "Der Achensee, auch 'Tirols größter See' genannt.".to_string(),
                },
                TourImage {
                    src: asset!("assets/images/tour4/1202Achensee.jpg").to_string(),
                    alt: "Achenseeweg am Westufer".to_string(),
                    caption: "Am Westufer verläuft der Achenseesteig.".to_string(),
                },
                TourImage {
                    src: asset!("assets/images/tour4/SouthTirolo.jpg").to_string(),
                    alt: "Hinab ins Tal nach Sudtirol".to_string(),
                    caption: "Abstieg nach Südtirol in Richtung Stein.".to_string(),
                },
            ],
        },
        Wandertour {
            id: 5,
            name: "Garmisch - Brixen Die anspruchsvolle Alpenüberquerung".to_string(),
            beschreibung: "Die etwas längere Alpenüberquerung. Beginnend mit der Partnachklamm am Fuße der Zugspitze, durch das Wettersteingebirge und die Mieminger Kette, durch die Stubaier und die Sarntaler Alpen bis nach Brixen. Bei unserer neuen, herausfordernden Tour benötigt es eine gute Portion Ausdauer!".to_string(),
            schwierigkeitsgrad: "Schwer".to_string(),
            etappen: vec![
                Etappe {
                    id: 21,
					name: "Partnachklamm - Reintal - Knorrhütte".to_string(),
                    beschreibung: "Nach der Begrüßung und einem kurzen Ausrüstungscheck geht es los. Durch die wunderschöne Partnachklamm und das Rheintal, vorbei an der Reintalangerhütte, 1369 m, erreichen wir unser Tagesziel – die Knorrhütte, 2051 m. Diese liegt in karger und felsiger Umgebung am Fuße der Zugspitze.".to_string(),
                    laenge_km: 17.7,
                    steigung_hm: 1370,
                    abstieg_hm: 60,
                    startort: "Garmisch-Partenkirchen, Bahnhof".to_string(),
                    zielort: "Knorrhütte".to_string(),
                    start_gps: GpsCoordinate::new(47.48308, 11.1171),
                    ziel_gps: GpsCoordinate::new(47.40997, 11.0127),
                },
                Etappe {
                    id: 22,
					name: "Gatterl - Hochfelder Alm - Sebensee - Coburger Hütte".to_string(),
                    beschreibung: "Verschiedene Landschaftsformen begegnen uns heute: Eine karge Felslandschaft, grüne Almwiesen und tiefblaue Seen. Von der Knorrhütte über das Gatterl, 2024 m, und hinab zur Hochfeldern Alm. In leichtem Auf und Ab zum wunderschönen Seebensee, 1675 m, der zu einer Pause einlädt. Ein letzter Anstieg führt uns zur Coburger Hütte, 1917 m, mit fantastischem Blick auf den Seebensee und Drachensee.".to_string(),
                    laenge_km: 13.0,
                    steigung_hm: 700,
                    abstieg_hm: 820,
                    startort: "Knorrhütte".to_string(),
                    zielort: "Coburger Hütte, Zugspitzmassiv".to_string(),
                    start_gps: GpsCoordinate::new(47.40997, 11.0127),
                    ziel_gps: GpsCoordinate::new(47.35997, 10.9336),
                },
				Etappe {
                    id: 23,
					name: "Coburger Hütte - Grünsteinscharte - Inntal - Sellraintal".to_string(),
                    beschreibung: "Nach dem Frühstück starten wir gemütlich bergauf zur Grünsteinscharte 2272 m. Weiter geht es hinab durch die Höllreise in die sogenannte Hölle. Der Abstieg führt über das Lehnberghaus zum Gasthof Arzkasten. Hier holt uns ein Taxi ab und bringt uns nach Lüsens ins Sellraintal. Transfer ca. 55 km, 1 Std.".to_string(),
                    laenge_km: 8.4,
                    steigung_hm: 470,
                    abstieg_hm: 1240,
                    startort: "Coburger Hütte, Zugspitzmassiv".to_string(),
                    zielort: "Lüsens im Sellraintal".to_string(),
                    start_gps: GpsCoordinate::new(47.35997, 10.9336),
                    ziel_gps: GpsCoordinate::new(47.1301, 11.1382),
                },
				Etappe {
                    id: 24,
					name: "Lüsens - Horntaler Joch - Franz-Senn-Hütte".to_string(),
                    beschreibung: "Wir starten von unserem Gasthof und wandern durch eine ursprüngliche Wald- und Almlandschaft hinauf zur Spielgruben. Durch das karge Horntal bis zum großen Horntaler Joch auf 2800 m. Optional können wir noch auf den Schafgrübler steigen 2922 m. Schon vom Joch sehen wir die Gletscher bedeckten Stubaier Berge. Aber auch die Ebene, in der die Franz-Senn-Hütte auf 2149 m steht, ist schon zu erkennen.".to_string(),
                    laenge_km: 7.8,
                    steigung_hm: 1190,
                    abstieg_hm: 680,
                    startort: "Lüsens im Sellraintal".to_string(),
                    zielort: "Franz-Senn-Hütte".to_string(),
                    start_gps: GpsCoordinate::new(47.1301, 11.1382),
                    ziel_gps: GpsCoordinate::new(47.08504, 11.16845),
                },
				Etappe {
                    id: 25,
					name: "Stubaier Höhenweg - Neue Regensburger Hütte - Stubaital".to_string(),
                    beschreibung: "Auf der heutigen Etappe folgen wir dem bekannten Stubaier Höhenweg. Wir wandern zunächst flach ins Kuhgschwetz. Durch die Platzengrube wird es etwas steiler und schließlich erreichen wir den Schrimmennieder. Von hier oben ist die Aussicht auf den Stubaier Hauptkamm grandios und es fällt schwer, bis zur Neuen Regensburger Hütte hinabzusteigen. Nach einer gemütlichen Pause geht es weiter hinab ins Stubaital. Übernachtung im Hotel.".to_string(),
                    laenge_km: 14.0,
                    steigung_hm: 600,
                    abstieg_hm: 1540,
                    startort: "Franz-Senn-Hütte".to_string(),
                    zielort: "Stubaital".to_string(),
                    start_gps: GpsCoordinate::new(47.08504, 11.16845),
                    ziel_gps: GpsCoordinate::new(47.0362, 11.2261),
                },
				Etappe {
                    id: 26,
					name: "Gschnitz - Tribulaunhütte".to_string(),
                    beschreibung: "Transfer nach Gschnitz. Aufstieg zur Gschnitzer Tribulaunhütte, 2064 m. Nach einer gemütlichen Rast weiter zur Pflerscher Scharte, 2599 m, die auch als Sandesjöchl bekannt ist und die Grenze zu Südtirol markiert. Von hier sieht man schon das Tagesziel - die italienische Tribulaunhütte, 2369 m, direkt am See.".to_string(),
                    laenge_km: 9.0,
                    steigung_hm: 1490,
                    abstieg_hm: 390,
                    startort: "Gschnitz".to_string(),
                    zielort: "Tribulaunhütte".to_string(),
                    start_gps: GpsCoordinate::new(47.0443, 11.3503),
                    ziel_gps: GpsCoordinate::new(47.00207, 11.34655),
                },
				Etappe {
                    id: 27,
					name: "Tribulaunhütte - Pflerschtal - Sterzingerhaus".to_string(),
                    beschreibung: "Heute steigen wir auf dem Wasserfallweg nach Steinjoggler ab. Von dort holt uns ein Taxi und bringt uns nach Vallming. Hier beginnen wir den Aufstieg zum Sterzingerhaus, wo wir heute übernachten. Auf dem Weg kommen wir an den drei Vallminger Almhütten Jörgner Kaser, Baron Kaser und Walter Kaser vorbei, wo wir einkehren können. Vom Sterzingerhaus haben wir eine tolle Aussicht über Sterzing.".to_string(),
                    laenge_km: 10.2,
                    steigung_hm: 760,
                    abstieg_hm: 980,
                    startort: "Tribulaunhütte".to_string(),
                    zielort: "Sterzingerhaus".to_string(),
                    start_gps: GpsCoordinate::new(47.00207, 11.3465),
                    ziel_gps: GpsCoordinate::new(46.91665, 11.39693),
                },
				Etappe {
                    id: 28,
					name: "Sterzing - Penser Joch - Flaggerschartenhütte".to_string(),
                    beschreibung: "Mit der Rosskopfbahn fahren wir nach Sterzing hinunter. Von dort fährt uns ein Taxi zum Penser Joch, 2211 m. Auf nun vergleichsweise einfachen Wegen wandern wir durch die einsamen Sarntaler Alpen. In stetigem Auf und Ab erreichen wir die kleine und urige Flaggerschartenhütte, 2481 m, am Flaggersee. ".to_string(),
                    laenge_km: 9.4,
                    steigung_hm: 720,
                    abstieg_hm: 460,
                    startort: "Sterzingerhaus".to_string(),
                    zielort: "Flaggerschartenhütte".to_string(),
                    start_gps: GpsCoordinate::new(46.91665, 11.39693),
                    ziel_gps: GpsCoordinate::new(46.7715, 11.48756),
                },
				Etappe {
                    id: 29,
					name: "Schalderertal - Brixen".to_string(),
                    beschreibung: "Über das Tellerjoch bis zur Schalderer Scharte, 2324 m. Vor uns liegt ein weitläufiger Talkessel. Auf dem sogenannten Wasserfallweg gelangen wir ins Schalderer Tal. Taxi nach Brixen.".to_string(),
                    laenge_km: 10.3,
                    steigung_hm: 430,
                    abstieg_hm: 1460,
                    startort: "Flaggerschartenhütte".to_string(),
                    zielort: "Brixen".to_string(),
                    start_gps: GpsCoordinate::new(46.7715, 11.48756),
                    ziel_gps: GpsCoordinate::new(46.710589, 11.6505),
                },
				Etappe {
                    id: 30,
					name: "Brixen - Garmisch (Taxitransfer)".to_string(),
                    beschreibung: "Fahrt über den Brenner, Innsbruck und Seefeld zurück nach Garmisch-Partenkirchen.".to_string(),
                    laenge_km: 0.0,
                    steigung_hm: 0,
                    abstieg_hm: 0,
                    startort: "Brixen".to_string(),
                    zielort: "Garmisch, Bahnhof".to_string(),
                    start_gps: GpsCoordinate::new(46.710589, 11.6505),
                    ziel_gps: GpsCoordinate::new(47.48308, 11.1171),
                },
            ],
            images: vec![
                TourImage {
                    src: asset!("assets/images/tour5/partnachklamm.jpg").to_string(),
                    alt: "Partnachklamm".to_string(),
                    caption: "Die beeindruckende Partnachklamm in Garmisch-Partenkirchen.".to_string(),
                },
                TourImage {
                    src: asset!("assets/images/tour5/knorrhuette.jpg").to_string(),
                    alt: "Knorrhütte".to_string(),
                    caption: "Die Knorrhütte am Fuße der Zugspitze.".to_string(),
                },
                TourImage {
                    src: asset!("assets/images/tour5/seebensee.jpg").to_string(),
                    alt: "Seebensee".to_string(),
                    caption: "Der malerische Seebensee in den Alpen.".to_string(),
                },
            ],
        },
    ]
}



